### ISSUE TITLE
Não retorna erro quando tem identificador inválido na linha

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#109]
classe Animal {
          correr() {
            escreva("Correndo Loucamente"); aquiPrecisaGerarUmErro
          }
        }
        classe Cachorro herda Animal {
          latir() {
            escreva("Au Au Au Au");
          }
        }

        var nomeDoCachorro = Cachorro();
        nomeDoCachorro.correr();
        nomeDoCachorro.latir();

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Me retornou o seguinte:

```
Correndo Loucamente
Erro: [Linha: 3] Variável não definida: 'aquiPrecisaGerarUmErro'.
```

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Nesse caso o retorno do erro vem do interpretador, penso que não deveria nem mesmo executar essa linha, deveria parar no Avaliador Sintático, estou certo?

**Comment by leonelsanchesdasilva** [comment]
> @leonelsanchesdasilva Nesse caso o retorno do erro vem do interpretador, penso que não deveria nem mesmo executar essa linha, deveria parar no Avaliador Sintático, estou certo?

Depende. A construção é válida no modo LAIR.

**Comment by leonelsanchesdasilva** [comment]
Não considero essa issue relevante no ponto em que estamos, mas se sentir que devemos reabri-la, fique à vontade.
