### ISSUE TITLE
Erro na função mapear quando o retorno da função de callback é passado sem ponto e vírgula

### ISSUE THREAD

**Issue by AlessandroFMello** [DesignLiquido/delegua#121]
```
funcao funcaoTestaMap(lista) {
  retorna mapear(
    lista,
    funcao(valor) {
      retorna valor
    })
}

escreva(funcaoTestaMap([1, 2, 3, 4]))
```
retorno:
NaN, NaN, NaN, NaN

```
funcao funcaoTestaMap(lista) {
  retorna mapear(
    lista,
    funcao(valor) {
      retorna valor;
    })
}

escreva(funcaoTestaMap([1, 2, 3, 4]))
```
retorno:
1, 2, 3, 4

**Comment by leonelsanchesdasilva** [comment]
@AlessandroFMello Aparentemente é alguma particularidade do Linux. Testei o primeiro exemplo com Windows e executou normalmente. 

Vou testar no Raspberry Pi e logo retorno aqui.

**Comment by leonelsanchesdasilva** [comment]
@AlessandroFMello Confirmei o problema no Raspberry Pi. Parece ser algum problema particular do Linux. Vou instalar uma VM com mais memória que o Raspberry Pi para verificar o que está acontecendo de fato.

**Comment by leonelsanchesdasilva** [comment]
@AlessandroFMello Bom, um pouco de Linux aqui:

No Linux, o final da linha é expresso por `\n`. No Windows, por `\r\n`. No Windows, portanto, sempre temos um símbolo que marca o final da linha. Isso é importante nessa lógica aqui (Lexador):

```ts
    avancar(): void {
        this.atual += 1;

        if (this.eFinalDaLinha() && !this.eUltimaLinha()) {
            this.linha++;
            this.atual = 0;
        }
    }
```

Como no Linux não há esse símbolo do final, o Lexador pula para a próxima linha ao acessar o último caractere (no caso, o 'r' de valor) e lê a próxima linha como a variável. Por isso o erro. 

O que vou fazer é colocar um símbolo do Linux mesmo ( '\0') como o finalizador de linha. Isso deve resolver.
