### ISSUE TITLE
Método 'escreva' retorna um 'undefined' a mais. 

### ISSUE THREAD

**Issue by VitBrandao** [DesignLiquido/delegua#140]
Se escrevermos somente o nome da variável no terminal e dermos um enter, o código retorna um objeto com as chaves "valor" e "tipo". Exemplo:
```
var texto = "Olá, tudo bem?"; // undefined
texto // {"valor":"Olá, tudo bem?","tipo":"texto"}
```
Até aqui, tudo bem, pois quando digitamos o nome da variável, o objeto contendo valor e tipo são retornados na íntegra.

Porém, se seguirmos o mesmo processo, mas utilizamos o método **escreva(variável)** para ler, o código retorna o valor, **mas seguido de um undefined na linha abaixo**:

```
var texto = "Olá, tudo bem?";
escreva(texto); 
// Olá, tudo bem? 
// undefined
```

**OBSERVAÇÕES FINAIS:**
- Pode ser que o método esteja tentando também retornar o "tipo" - a segunda chave do objeto montado ao criar a variável;
- É importante notar também que no primeiro exemplo, após criar a variável, um undefined também está sendo retornado por padrão. Trago esse ponto apenas para a possibilidade de ser o mesmo erro ou uma questão similar.

**Comment by samuelrvg** [comment]
@VitBrandao Já iniciou essa ISSUE ?

Se não, eu posso fazer ela, visto que já tenho uma base de como resolver, ou, se preferir posso te ajudar com essa ISSUE.

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Pode fazer, por favor.
