### ISSUE TITLE
Mau funcionamento ao tentar clonar variáveis

### ISSUE THREAD

**Issue by VitBrandao** [DesignLiquido/delegua#150]
Ao tentar clonar uma variável a partir de outra, essa nova variável está recebendo o **objeto inteiro** ("valor" e "tipo") ao invés de receber somente o valor.

Exemplo:

```
var a = 123;
var copia = a;
escreva(copia); // {"valor":{"valor":123,"tipo":"número"},"tipo":"dicionário"}
```

Estou ciente de que clonar dessa forma pode ser um pouco incomum, mas nunca podemos duvidar do comportamento do usuário. 

Podemos notar também que outra consequência dessa Issue é que as variáveis clonadas sempre receberão o tipo '**dicionário**' por receberem o objeto inteiro.

Em tempo, ressalto que quando clonamos uma variável com implementações extras (o que é mais comum), o funcionamento **ocorre de acordo:**

```
var a = 'Vitor Brandao';
var aMaiusculo = a.maiusculo();
escreva(aMaiusculo); // "VITOR BRANDAO"
```
Mas mesmo ao tentar clonar a variável bem sucedida, persiste a atribuição do objeto inteiro:

```
var a = 'Vitor Brandao';
var aMaiusculo = a.maiusculo();
var copia = aMaiusculo;
escreva(copia); // {"valor":{"valor":"VITOR BRANDAO","tipo":"texto"},"tipo":"dicionário"}
```

**Comment by leonelsanchesdasilva** [comment]
https://github.com/DesignLiquido/delegua/pull/151
