### ISSUE TITLE
Corrigir Bug no lexador do dialeto birl.

### ISSUE THREAD

**Issue by ItaloCobains** [DesignLiquido/delegua#160]
Se a string de `this.codigo` não vinher com os `\n` nos locais certos o lexador entra em uma verificação infinita.

Meu proximo passo e corrigir esse bug.

**Comment by leonelsanchesdasilva** [comment]
@ItaloCobains O Dialeto Égua Clássico trabalha dessa forma também. Eu consultaria o código do importador e veria como os `\n` são incluídos quando o arquivo é importado. 

Para os testes unitários, eu colocaria os `\n` na mão mesmo.

**Comment by ItaloCobains** [comment]
Entendi, Vou fazer as devidas alterações quando tiver tudo correto eu fecho o issues.
