### ISSUE TITLE
Parênteses em `retorna` devem ser opcionais

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#175]
`inicio.delegua`

    var funcoesMatematicas = importar('./funcoes.delegua')

    var soma = funcoesMatematicas.soma(1, 2)
    escreva(soma)

`funcoes.delegua`

    função soma(valor1, valor2){
        retorna valor1 + valor2;
    }

```
delegua inicio.delegua
```

> Erro: [Linha: 3] Chamada de função ou método inexistente: [object Object]

**Comment by leonelsanchesdasilva** [comment]
`retorna` requer parênteses pra funcionar:

`retorna valor1 + valor2;`

Vou deixar o uso de parênteses opcional.

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/delegua/pull/177.
