### ISSUE TITLE
Melhorar validação e mensagem de erro em `leia`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#209]
Mensagem de erro não condiz com o teste.

`var nome = leia('Digite o seu nome:' 1111)`

> [Linha: 15] Erro no '123': Esperado ')' após os valores em leia.

**Comment by samuelrvg** [comment]
A PR #217 ainda não resolve o problema.

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg "ainda não resolve o problema" é deveras vago. Estou fechando este item. Fique à vontade para reabrir com uma descrição mais completa do problema.
