### ISSUE TITLE
Permitir concatenação de texto e número

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#21]
Essa funcionalidade é para o `dialeto` Delégua.

**Comment by leonelsanchesdasilva** [comment]
Concatenar texto e número deve resolver para texto.

**Comment by samuelrvg** [comment]
Essa ISSUE depende dessa outra.

#23

**Comment by samuelrvg** [comment]
https://github.com/DesignLiquido/delegua/pull/35
