### ISSUE TITLE
Deixar opcional o uso de (ponto e vírgula) no final

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#22]

**Comment by leonelsanchesdasilva** [comment]
Aqui e um ponto que iremos divergir da Égua original. Devemos ter uma forma de indicar na execução qual nível de compatibilidade iremos usar. Se é Égua ou Delégua.

**Comment by samuelrvg** [comment]
Isso vai gerar alguns vários `if's` em todo o projeto. A princípio já consegui fazer funcionar o uso opcional do ponto e virgula, mas com isso, precisaria definir agora a melhor forma de escolher qual usar, se Égua ou Delégua.

**Comment by samuelrvg** [comment]
Vai influênciar nessas ISSUE's também.

- https://github.com/DesignLiquido/delegua/issues/21
- https://github.com/DesignLiquido/delegua/issues/15

**Comment by samuelrvg** [comment]
Essa ISSUE depende dessa outra.

#23

**Comment by samuelrvg** [comment]
Depende da resolução dessa outra ISSUE https://github.com/DesignLiquido/delegua/issues/41

**Comment by samuelrvg** [comment]
Resolvido na PR https://github.com/DesignLiquido/delegua/pull/43
