### ISSUE TITLE
Adicionar flag para saber qual linguagem usar, egua ou delégua

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#23]
Padrão é `delegua`.

**Comment by leonelsanchesdasilva** [comment]
Sugestão: `--dialeto`. Padrão é `delegua`.

Outros dialetos:

- `egua`
- `eguac`
- `eguap`

**Comment by leonelsanchesdasilva** [comment]
https://github.com/DesignLiquido/delegua/pull/35
