### ISSUE TITLE
Alterar CodeFlask Editor para Monaco Editor

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#231]
Com isso, conseguimos melhorar o editor com novas funcionalidades, uma delas é mencionada nessa ISSUE da linguagem égua https://github.com/eguatech/egua/issues/159

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Essa issue pertence a https://github.com/DesignLiquido/delegua-web. Favor abrir lá.

**Comment by samuelrvg** [comment]
Aberto issue em delegua-web https://github.com/DesignLiquido/delegua-web/issues/17
