### ISSUE TITLE
Adicionar no Wiki diferenças do égua e delégua

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#24]
Algumas delas:

- https://github.com/DesignLiquido/delegua/issues/23
- https://github.com/DesignLiquido/delegua/issues/15
- https://github.com/DesignLiquido/delegua/issues/21
- https://github.com/DesignLiquido/delegua/issues/22
- https://github.com/DesignLiquido/delegua/issues/3
- https://github.com/DesignLiquido/delegua/issues/45

**Comment by leonelsanchesdasilva** [comment]
https://github.com/DesignLiquido/delegua/wiki/Dialetos
