### ISSUE TITLE
Erro teste unitário Éguap -> interpretador -> Classes -> Trivial

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#243]
Erros:

> Variável não definida: 'latir'.
> Variável não definida: 'correr'.
> Método indefinido não recuperado.

**Comment by leonelsanchesdasilva** [comment]
Problema não mais existe na versão 0.12.5. O teste foi descomentado e funciona normalmente.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva O problema ainda persiste:

![image](https://user-images.githubusercontent.com/14062631/215375738-60a47a1e-da15-43ad-b17a-b820fcda02a6.png)

**Comment by leonelsanchesdasilva** [comment]
[Em EguaP cada método requer a palavra função na frente.](https://github.com/DesignLiquido/delegua/wiki/Dialetos#eguap)
