### ISSUE TITLE
Como fazer importação de classe?

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#255]

**Comment by leonelsanchesdasilva** [comment]
Em teoria apenas importar o arquivo com a declaração de classe já deveria ser suficiente.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Tentei da seguinte forma:

`iniciar.delegua`

```
var cachorro = importar('./objetos/cachorro.delegua')

escreva(cachorro.nome())
```

`cachorro.delegua`

```
classe Cachorro {
    construtor(){
    }

    funcao nome(){
        escreva('Meu nome é Hulk')
    }
}
```

Erros:
> [Linha: undefined] Erro em JavaScript: undefined
> Pilha de execução: undefined
> Erro: [Linha: 3] Chamada de função ou método inexistente: [object Object]

**Comment by leonelsanchesdasilva** [comment]
Isto aqui não funciona porque `cachorro` não é um objeto, e sim um módulo:

```js
var cachorro = importar('./objetos/cachorro.delegua')

escreva(cachorro.nome())
```

Ou seja, a declaração deveria ser algo assim:

```js
var moduloCachorro = importar('./objetos/cachorro.delegua')

var cachorro = moduloCachorro.Cachorro()
escreva(cachorro.nome())
```

Em outras palavras, a importação devolve um módulo, que tem uma declaração de classe dentro, e que aí você pode instanciar chamando o construtor.

**Comment by leonelsanchesdasilva** [comment]
A versão 0.12.5 funciona conforme o exemplo do comentário anterior.
