### ISSUE TITLE
Importação de arquivos com declaração de classe devolve um módulo vazio

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#256]
Testar seguinte cenário:

`iniciar.delegua`
│   ├── objetos
│    │   └── `animal.delegua`
│    │   └── `cachorro.delegua`

O arquivo `iniciar.delegua` deve importar o arquivo `./objetos/cachorro.delegua` e `cachorro.delegua`, fazer a importação de `animal.delegua`

Executar `delegua iniciar.delegua`

Erros:

> [Linha: undefined] Erro em JavaScript: undefined
> Pilha de execução: undefined

**Comment by leonelsanchesdasilva** [comment]
Este foi o teste?

```js
importar('./objetos/animal.delegua')
importar('./objetos/cachorro.delegua')

var thor = Cachorro();
thor.corre();
```

**Comment by leonelsanchesdasilva** [comment]
Exemplo refinado:

```js
var cachorro = importar('./objetos/cachorro.delegua')

var thor = cachorro.Cachorro()
thor.corre()
```

O módulo gerado vem vazio. Deveria vir com uma declaração de classe:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/53848829/215345743-92f96d3d-5214-4e69-9780-8436200251d6.png">
