### ISSUE TITLE
Valores de entrada não funcionam

### ISSUE THREAD

**Issue by jpparella** [DesignLiquido/delegua#302]
Estava planejando uma aula para meus alunos e presenciei esse problema na hora de executar o código 
Ele trava na hora que chega em "resultado = n1*n2", inclusive debugando pelo visual studio code com a extensão, ou até mesmo pelo link "https://designliquido.github.io/delegua-web/"

código com erro (tentei de diversas formas corrigir, nada solucionou até agora):

```
var n1 = 1;
var n2 = 1; 
var resultado = 0

var n1 = leia("teste 1");

enquanto (verdadeiro){
    var menu = leia("Digite a opção: 1 - Multiplicacao / 2 - Divisao / 3 - Soma / 4 - Subtração");
    se (menu == "1"){
        resultado = n1 * n2;        
        sustar;
    }senao se(menu =="2"){
        resultado = n1 / n2;
        sustar;            
    }senao se(menu =="3"){
        resultado = n1 + n2;
        sustar;            
    }senao se(menu =="4"){
        resultado = n1 - n2;
        sustar;
    }senao{
        escreva("opção invalida");
    }
}
escreva("resultado "+resultado);
```

Estava tendo problemas ao utilizar as variaveis direto da entrada, então comecei a atribuir o valor 1 na variavel antes de pedir ela por entrada, parece que a tipagem se perde quando é passada pela entrada
um dos problema que enfrentei foi nesse código:

```
var n1 = 1;
var n1 = leia("digite sua idade");
var n2 = (365*n1);

escreva("Você tem " +n2+" dias de vida");
```

Sem a primeira linha não conseguia calcular corretamente, ele repetia 365 vezes o valor digitado
Depois de colocar ele resolveu o problema, mas pelo que vi pelo editor online também não funciona assim.

**Comment by leonelsanchesdasilva** [comment]
Olá, @jpparella. Bem-vindo e obrigado pela issue. 

Farei a correção do bug e te aviso por aqui quando estiver pronto.

**Comment by leonelsanchesdasilva** [comment]
@jpparella Uma atualização aqui: o núcleo da linguagem e a biblioteca Node estão ok pelos testes unitários. 

De fato, identifiquei três bugs diferentes através dos seus testes:

- https://github.com/DesignLiquido/vscode/issues/6
- https://github.com/DesignLiquido/vscode/issues/7
- https://github.com/DesignLiquido/delegua-web/issues/26

Você gostaria de acompanhar os itens individualmente, ou gostaria de seguir apenas esta issue?

**Comment by leonelsanchesdasilva** [comment]
@jpparella Hoje lançamos a versão 0.3.9 da extensão, o que deve resolver todos os problemas reportados aqui: https://marketplace.visualstudio.com/items?itemName=designliquido.designliquido-vscode. 

Fique à vontade para reabrir essa issue se algum desses problemas persistir.
