### ISSUE TITLE
Erro ao atribuir numero a outra variável

### ISSUE THREAD

**Issue by jpparella** [DesignLiquido/delegua#304]
Estava testando um código de ordenação quando me deparei com um erro, tanto no visual studio code quanto no editor online
No código abaixo quando se tenta atribuir os valores nX ao valor a,b ou c, ele atribui nulo ou um objeto errado.

```
var n1 = 1;
var n1 = leia("digite o numero1");
var n2 = 1;
var n2 = leia("digite o numero2");
var n3 = 1;
var n3 = leia("digite o numero3");


var a = n1;
var b = n2;
var c = n3;

se (n1 > n2 e n1 > n3){
    c = n1;
    se (n2 > n3){
        a = n3;
        b = n2;
    }senao{
        a = n2;
        b = n3;
    }
}senao se (n2 > n1 e n2 > n3){
    c = n2;
    se (n1 > n3){
        a = n3;
        b = n1;
    }senao{
        a = n1;
        b = n3;
    }
}senao {
    c = n3;
    se (n2 > n1){
         a = n1;
         b = n2;
    }senao{
         a = n2;
         b = n1;
    }
}

escreva("ordem crescente "+a+" - "+b+" - "+ c);
```

no editor online apresenta a saida:

```
ordem crescente [object Object] - [object Object] - [object Object]
```

**Comment by leonelsanchesdasilva** [comment]
Olá, @jpparella. Obrigado por mais uma issue. 

Testei seu código no VSCode agora mesmo e tive o seguinte:

![image](https://user-images.githubusercontent.com/53848829/228884257-5ffb9dbe-1467-4ddd-95b0-94a42f204ad1.png)

Pode ser que tenhamos que fazer um ajuste na versão online. Se assim for, atualizo essa issue com mais detalhes.

**Comment by leonelsanchesdasilva** [comment]
Issue relacionada: https://github.com/DesignLiquido/delegua-web/issues/27

**Comment by leonelsanchesdasilva** [comment]
@jpparella A correção já está no ar. Estou fechando a issue.
