### ISSUE TITLE
Não é armazenado corretamente o valor do "Leia()" 

### ISSUE THREAD

**Issue by jpparella** [DesignLiquido/delegua#311]
Ao rodar o comando LEIA dentro do laço de repetição PARA, não é possível gravar corretamente os valores, ele repete o primeiro valor informado.

```
var vetor = [];

para (var i = 0; i < 5; i = i + 1) {
    
    var n1 = leia("Digite o numero ");
    vetor[i] = inteiro(n1);
}
escreva(vetor);


```

**Comment by samuelrvg** [comment]
Olá @jpparella, fiz o teste no [editor web](https://designliquido.github.io/delegua-web/) de Delégua, e me pareceu normal o comportamento.

![image](https://user-images.githubusercontent.com/14062631/230080224-65b7a0e8-4444-4faa-a3fc-11bb3beff004.png)

Veja se esta com a [versão](https://github.com/DesignLiquido/delegua/releases/tag/0.15.13) atual de Delégua na sua máquina.

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Consegui simular o problema na extensão do VSCode. Já estou trabalhando na solução.

**Comment by leonelsanchesdasilva** [comment]
@jpparella @samuelrvg https://github.com/DesignLiquido/delegua/pull/312 resolve o problema. Havendo o merge, farei a publicação de versão na extensão.
