### ISSUE TITLE
Método com declaração de constante retornando `nulo`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#338]
Testando o seguinte cenário:

```
const esc = funcao(){
  const x = '1'
  retorna x;
}

escreva(esc())
// nulo
```

Estou obtendo um retorno `nulo` de `escreva`, sendo que o correto seria retornar o valor da constante `x` do método `esc`.

`var` também ocorre o mesmo.

**Comment by samuelrvg** [comment]
Problema acontece somente em `0.17.4` da [solução delégua](https://www.npmjs.com/package/delegua), atualizar para versão `0.17.5` já resolve o problema.

@leonelsanchesdasilva Assim que atualizar, pode fechar essa ISSUE, fazendo favor.

**Comment by leonelsanchesdasilva** [comment]
https://github.com/DesignLiquido/delegua-completo/commit/df9665d51c8ea0e787df5e28f01dbba163f80884
