### ISSUE TITLE
Não usar o package.json para definir a versão atual.

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/delegua#36]

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva 

Nas minhas pesquisas, eu não consegui encontrar outra forma de definir a versão atual, que não seja pelo package.json.

A última alteração que fiz no método pela PR https://github.com/DesignLiquido/delegua/pull/51 melhora ao obter a versão do package.json.

Teria alguma sugestão do que poderiamos fazer pra automatizar ou melhorar o que já temos?

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Acho que podemos simplesmente fechar essa issue. Só preciso ver uma forma de fazer a linguagem ler do diretório certo (atualmente dá erro, mas coloquei um catch).

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva 

A PR #51 resolve esse problema, não esta caindo mais no catch como antes.
