### ISSUE TITLE
Alguns erros não estão sendo retornados no vetor erros.

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#360]
Se executo com interpretador um código com uma variável não definida  é esperado que esse erro seja retornado no vetor erros.

```
teste
escreva("Qualquer coisa")
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/b5e19ab3-f72e-4495-ad4f-3becea57cd30)
<br>
Até aí tudo bem, porém alguns erros não estão sendo retornados dentro desse vetor, como nesse caso:
```
nescreva("Qualquer coisa")
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/d0c3596f-2728-497e-89f2-ef4306e2c79b)

<br>
Aqui está mais um exemplo:

![image](https://github.com/DesignLiquido/delegua/assets/93893533/3c09bb56-3cd6-4f83-b801-c103c6d1b4f6)

Eu percebi isso em outros casos também, só que não estou lembrando agora.

**Comment by samuelrvg** [comment]
Resolvido na release [0.20.2](https://github.com/DesignLiquido/delegua/releases/tag/0.20.2)
