### ISSUE TITLE
Método encaixar() está inserindo null no vetor

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#367]
Tenho o seguinte código:

```
var numeros = [1, 2, 3, 4]

numeros.encaixar(0, 3);

escreva(numeros);
```

Em vez de resultar em um vetor contendo apenas o 4, o método `encaixar()` está substituindo os elementos removidos por `null`:

![image](https://github.com/DesignLiquido/delegua/assets/93893533/8b08257e-b906-4320-8f2f-d2f47226d6df)

**Comment by samuelrvg** [comment]
@JohnPetros Adicionei um parâmetro opcional a mais, visto que o método `splice` do `JavaScript` tanto modifica o vetor quanto retorna seus valores, veja como ficou https://github.com/DesignLiquido/delegua/pull/368/files

**Comment by samuelrvg** [comment]
Veja [release](https://github.com/DesignLiquido/delegua/releases/tag/0.20.5) qualquer coisa, pode reabrir a ISSUE.

**Comment by samuelrvg** [comment]
@JohnPetros Refazendo alguns testes, dessa forma também vai funcionar agora😄 

````
var numeros = [1, 2, 3, 4]

numeros.encaixar(0, 3);

escreva(numeros); // 4
````
