### ISSUE TITLE
Método encaixar não está retornando os itens removidos de um vetor

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#369]
Estou removendo os três primeiros itens do vetor frutas:

```
var frutas = ["maçã", "banana", "morango", "laranja", "uva"]

var alimentos = frutas.encaixar(0, 3);
escreva(alimentos);
```

Só que em vez de retornar as três primeiras frutas na variável alimentos (maçã, banana e morango), está retornando apenas os que sobraram no vetor (laranja e uva):

![image](https://github.com/DesignLiquido/delegua/assets/93893533/acf57dde-7b0b-4df3-8fd2-db3f82c940f3)

**Comment by samuelrvg** [comment]
@JohnPetros Fiz uma correção para permitir passagem de `nulo` como parâmetro, no seu caso, vai ficar da seguinte forma.

````
var frutas = ["maçã", "banana", "morango", "laranja", "uva"]

var alimentos = frutas.encaixar(0, 3, nulo, verdadeiro);
escreva(alimentos);
````

Atualizar para versão: 0.20.6

**Comment by JohnPetros** [comment]
O que seria esse terceiro e quarto parâmetro do `encaixar`?
