### ISSUE TITLE
Método concatenar não está funcionando com textos

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#374]
Ao usar o método `concatenar` em textos é retornado erro.

```
var mensagem = "Olá ";
        
mensagem.concatenar(", mundo!");

escreva(mensagem);
```

**Comment by samuelrvg** [comment]
@JohnPetros Eu tinha feito somente para vetor, estou fazendo agora para texto também.

**Comment by samuelrvg** [comment]
PR: https://github.com/DesignLiquido/delegua/pull/375

Assim que gerar nova versão eu coloco aqui e encerro a ISSUE.

**Comment by samuelrvg** [comment]
Versão 0.20.9 lançada com essa nova melhoria.
