### ISSUE TITLE
Permitir usar regex no método substituir

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#376]
Ao usar o `substituir` é substituido a primeira ocorrência do valor pesquisado:

```
var str = "olá mundo, olá universo";
var novaStr = str.substituir("olá", "oi");
escreva(novaStr); // "oi mundo, olá universo"
```

Porém, eu queria poder usar regex para substituir todas as ocorrências de uma vez.

```
var str = "olá mundo, olá universo";
var novaStr = str.substituir(/olá/g, "oi");
escreva(novaStr); // "oi mundo, oi universo"
```

<br>
É possível em Delégua?

**Comment by leonelsanchesdasilva** [comment]
Atualmente Delégua não suporta expressões regulares, mas acho uma funcionalidade excelente para implementarmos.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Como estamos falando de primitivas, não seria apenas verificar se o parâmetro passado é uma expressão regular?

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Tem algumas formas de fazer isso. Uma delas é usar o mesmo formato do JavaScript, o que significa aumentar a lógica do símbolo após a barra. Em outras palavras, teríamos que verificar se há outra barra na mesma linha e o que está entre duas barras faz sentido ou não, o que aumenta deveras a complexidade do Lexador. 

Uma outra forma de uso é aceitando expressões regulares através de textos, como é hoje na grande maioria das linguagens. Tendo isso, teríamos que avaliar qual motor de RegEx iríamos herdar. Creio que o do JavaScript mesmo, por questões de diminuição de complexidade.

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg @JohnPetros Estou querendo ir com o mesmo padrão de JavaScript para Regex, só mudando o símbolo que indica o literal Regex. 

Em vez de:

`/olá/gi`

Pensei em usar

`||olá||gi`

Alguns motivos pra isso:

- Complexidade do lexador: muita coisa já usa a barra: `/`. Queria usar outro símbolo;
- Um pipe apenas tem significado em Regex;
- O resto das convenções de Regex em JS mantemos, incluindo os caracteres após o símbolo de fechamento.
