### ISSUE TITLE
Permitir execução de métodos diretamente nos valores

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#379]
É possível executar métodos diretamente nos valores sem a necessidade de atribuí-los a variáveis primeiro?

Por exemplo com textos:
```
var mensagem = "OLÁ MUNDO".minusculo();
escreva(mensagem); //  olá, mundo
```

ou com vetores:
```
var frase = ["Olá", "mundo!"].juntar(", ");
escreva(frase); // Olá, mundo!
```

**Comment by leonelsanchesdasilva** [comment]
Oi, @JohnPetros. Sim, porque são primitivas. 

Se as situações descritas não funcionam, é bug.

**Comment by JohnPetros** [comment]
@leonelsanchesdasilva eu tentei, mas deu erro.

**Comment by samuelrvg** [comment]
Corrigido na [versão 0.20.10](https://github.com/DesignLiquido/delegua/releases/tag/0.20.10).
