### ISSUE TITLE
Resultado é null quando uma função retorna diretamente um vetor

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#380]
Essa função ao retornar um vetor, o resultado é dado como null em vez do vetor retornado:
```
funcao executar() {
  retorna [1, 2, 3]
}
executar()
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/71ac52dc-2e98-4d09-b9a3-fb1fe3a4f180)

**Comment by samuelrvg** [comment]
Resolvido na [versão 0.20.12](https://github.com/DesignLiquido/delegua/releases/tag/0.20.12).
