### ISSUE TITLE
Execução dá erro se é executado método em parâmetro de função

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#381]
Se um vetor passado como parâmetro de uma função executa um método, dá erro de execução.

```
funcao escreverMensagem(vetor) {
  se (vetor.inclui('mundo')) {
      escreva(vetor);
  }
}

escreverMensagem(["Olá", "mundo"]);
```

Também dá erro mesmo se o parâmetro for um texto.
```
funcao escreverMensagem(texto) {
  se (texto.inclui('mundo')) {
      escreva(texto);
  }
}

escreverMensagem("Olá, mundo");
```

![image](https://github.com/DesignLiquido/delegua/assets/93893533/04e529ba-9c8c-4856-9792-7499455681fa)

**Comment by samuelrvg** [comment]
Já tenho uma noção de como resolver.

**Comment by samuelrvg** [comment]
Esse problema foi resolvido na [versão](https://github.com/DesignLiquido/delegua/releases/tag/0.20.10)

**Comment by samuelrvg** [comment]
Corrigido na [versão 0.20.10](https://github.com/DesignLiquido/delegua/releases/tag/0.20.10).
