### ISSUE TITLE
Dá erro de execução se é acrescido um ponto e vírgula no final do laço para

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#382]
Se eu adicionar um ponto e vírgula na chave que fecha o laço `para` dá erro de execução.
```
para (var i = 0; i < 5; i++) {
  escreva(i);
};
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/582ace8f-db5a-41e3-9ba1-e13db1ac4270)

Mas caso não tenha esse ponto e vírgula a execução ocorre normalmente.
```
para (var i = 0; i < 5; i++) {
  escreva(i);
}
```

![image](https://github.com/DesignLiquido/delegua/assets/93893533/2a72d1a9-9e9c-416d-ada7-c8e3c8e1133e)

**Comment by samuelrvg** [comment]
Resolvido na [versão 0.20.11](https://github.com/DesignLiquido/delegua/releases/tag/0.20.11).
