### ISSUE TITLE
Interpolação não está funcionando com funções e expressões

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#384]
Se eu uso interpolação com uma variável, funciona corretamente:
```
var minha_variavel = "Strogonoff";
escreva('Eu gosto de ${minha_variavel}') 
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/72cbafd0-58bb-407d-9b26-941265b18742)
<br>

Porém, com uma função não:
```
funcao somar(num1, num2) {
  retorna num1 + num2;
}
escreva('a soma é ${somar(5 + 5)}');
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/b6a44248-d05d-470e-878f-ba692edb3b99)
<br>

Nem com uma expressão:
```
escreva('a soma é ${2 + 2}');
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/e7de75d8-fcbd-45a3-aba0-4191f66fef9d)

**Comment by leonelsanchesdasilva** [comment]
@JohnPetros Na verdade isso é uma funcionalidade nova. Até então Delégua resolve apenas variáveis na interpolação, mas vai ser show ter resolução de funções também.

**Comment by samuelrvg** [comment]
Resolvido na PR https://github.com/DesignLiquido/delegua/pull/390 e publicado na [versão 0.20.14](https://github.com/DesignLiquido/delegua/releases/tag/0.20.14)
