### ISSUE TITLE
Método encaixar não retorna os valores removidos de um vetor

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#414]
Um dos comportamentos esperados do método `encaixar` seria retornar os valores removidos de um vetor, mas parece que ele está retornando o próprio vetor.

```
var frutas = ['Banana', 'Laranja', 'Limao', 'Maçã', 'Manga'];
var citricos = frutas.encaixar(1, 2);

escreva(citricos);
```

![image](https://github.com/DesignLiquido/delegua/assets/93893533/4b3e3254-9b66-4050-b76b-82975652afd9)

**Comment by samuelrvg** [comment]
@JohnPetros Testa a [versão 0.21.11](https://github.com/DesignLiquido/delegua/releases/tag/0.21.11) se o problema persistir, pode reabrir a ISSUE.
