### ISSUE TITLE
Verificar possíveis erros duplicados em Delégua

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#418]

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Isso aqui ainda é relevante?

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Não acho que seja mais relevante, tinha aberto essa ISSUE pois Delégua esta retornando erros duplicados em delegua-web, mas isso acontece por causa do avaliador semântico, creio que um filtro na hora de mostrar o erro já deva resolver.
