### ISSUE TITLE
Atualizar wiki

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#419]
Atualizar a wiki com base nessas implementações recentes.

- [x] Falhar
- [x] Tipo De
- [x] Tradução de Delégua para Python
- [x] Declarar N variáveis na mesma linha
- [x] Novas formas de iniciar os tradutores
  - [x] `delegua-para-javascript`
  - [x] `delegua-para-js`
  - [x] `delegua-para-python`
  - [x] `delegua-para-py`
  - [x] `js-para-delegua`
  - [x] `javascript-para-delegua`
  - [x] `visualg-para-delegua`

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Creio que alguns desses tópicos sejam da Wiki de `delegua-node`.

**Comment by samuelrvg** [comment]
> @samuelrvg Creio que alguns desses tópicos sejam da Wiki de `delegua-node`.

Diz os tradutores? Mesmo a implementação estando em Delégua? Se for o caso, não seria interessante ter nas duas wiki's?

**Comment by leonelsanchesdasilva** [comment]
Acho que cada Wiki pode explicar uma parte. Aqui podemos explicar que deixamos os comandos disponíveis, enquanto que em `delegua-node` explicamos como os comandos são consumidos.
