### ISSUE TITLE
Traduzir funções nativas de `Delégua` para funções equivalentes em `Python`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#423]
https://github.com/DesignLiquido/delegua/issues/423#issuecomment-1880288304

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Pode por favor descrever isso melhor? Quais funções devem ser traduzidas, e quais são suas equivalentes?

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva Basicamente todas as funções globais, usar como referência:

[primitivas-vetor](https://github.com/DesignLiquido/delegua/blob/principal/fontes/bibliotecas/primitivas-vetor.ts)
[primitivas-texto](https://github.com/DesignLiquido/delegua/blob/principal/fontes/bibliotecas/primitivas-texto.ts)

Exemplo, em Delégua temos o `.adicionar`/`.empilhar` para inserir um item no vetor, quando traduzimos delégua pra javascript, temos o retorno da função `.push`. 

Logo em Delégua seria traduzir `.adicionar`/`.empilhar` para `.append`.

Pode ser usado como base o que fiz na tradução de Delégua para JavaScript que esta no arquivo:

[tradudor-javascript](https://github.com/DesignLiquido/delegua/blob/7ab4b5a17ef0073c27bb235940eb023d1d201a3f/fontes/tradutores/tradutor-javascript.ts#L98C12-L98C12) método base `traduzirFuncoesNativas(...)`

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/delegua/pull/571 pelo @Aristidescosta.
