### ISSUE TITLE
Método encaixar não está adicionando mais de um elemento em um vetor

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#445]
O método `encaixar` permite adicionar elementos em um vetor

```
var numeros = [1, 2, 3, 4, 5];
    
numeros.encaixar(1, 3, "texto1");
    
escreva(numeros);
``` 
![image](https://github.com/DesignLiquido/delegua/assets/93893533/eaa1cd57-d615-46fe-8f5a-283b1c89a992)

Contudo, não é possível adicionar mais de um elemento
```
var numeros = [1, 2, 3, 4, 5];
    
numeros.encaixar(1, 3, "texto1", "texto2");
    
escreva(numeros);
``` 
![image](https://github.com/DesignLiquido/delegua/assets/93893533/ac34668c-a285-449c-8289-e14a236635f5)

**Comment by samuelrvg** [comment]
Relacionado: https://github.com/DesignLiquido/delegua/issues/414

**Comment by samuelrvg** [comment]
Estou testando algumas coisas pra poder reescrever o método `encaixar` e assim resolver os problema que estão surgindo.

Branch: https://github.com/DesignLiquido/delegua/tree/metodo-encaixar-reescrita

**Comment by samuelrvg** [comment]
@JohnPetros [versão 0.21.11](https://github.com/DesignLiquido/delegua/releases/tag/0.21.11)
