### ISSUE TITLE
Interpolação de texto está sendo feita da maneira esperada

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#450]
Quando uso interpolação de texto, a impressão não é feita da maneira correta

```
var minha_variavel = "Strogonoff"
escreva("Eu gosto de ${minha_variavel}")
```

![image](https://github.com/DesignLiquido/delegua/assets/93893533/9c6680f2-0077-428d-8e39-18718cf1d72c)

**Comment by samuelrvg** [comment]
Corrigido na [versão 0.21.8](https://github.com/DesignLiquido/delegua/releases/tag/0.21.8)
