### ISSUE TITLE
Interpolação com valores lógicos ainda não ocorre da maneira esperada

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#451]
A questão da interpolação citada na issue #450 foi corrigida  exceto nos casos em que tento interpolar um valor lógico. 

```
var logico = falso
escreva('Valor: ${logico}')
```
![image](https://github.com/DesignLiquido/delegua/assets/93893533/8086a1c2-a102-429c-86b3-d7e0e1bbc2a5)

**Comment by samuelrvg** [comment]
Ótimo, não tinha testado esse cenário, resolvo assim que chegar em casa.

**Comment by samuelrvg** [comment]
Corrigido na [versão 0.21.9](https://github.com/DesignLiquido/delegua/releases/tag/0.21.9)
