### ISSUE TITLE
Adicionar na documentação sobre tipagem de funções

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#459]
Referência: https://github.com/DesignLiquido/delegua/discussions/438

**Comment by leonelsanchesdasilva** [comment]
- https://github.com/DesignLiquido/delegua/wiki/Estruturas-de-dados-elementares#tipos-de-dados
- https://github.com/DesignLiquido/delegua/wiki/Tipos-e-Infer%C3%AAncia-de-vari%C3%A1veis
