### ISSUE TITLE
Implementar tipagem para vetores

### ISSUE THREAD

**Issue by ItaloCobains** [DesignLiquido/delegua#461]
Preciso de um tipagem para os vetores pois assembly script não aceita array sem tipo.

```ts
export function add(): f64[] {
  let a: f64[] = [];
  a[0] = 1;
  a[1] = a[0];
  return a
}

export function add2(): f64[] {
    let a = [];
    a[0] = 1;
    a[1] = a[0];
    return a
}
```

![image](https://github.com/DesignLiquido/delegua/assets/83548040/e9f7a2ce-9162-4ab7-9fd5-58700fed74b4)

**Comment by leonelsanchesdasilva** [comment]
Veja se isso te atende, por favor:

- https://github.com/DesignLiquido/delegua/blob/56fa8e2c2545c9dd9efa37486468770227a338ad/fontes/interfaces/variavel-interface.ts#L15
- https://github.com/DesignLiquido/delegua/blob/56fa8e2c2545c9dd9efa37486468770227a338ad/fontes/interpretador/interpretador-base.ts#L1007

**Comment by samuelrvg** [comment]
@ItaloCobains @leonelsanchesdasilva Depois que essa [PR](https://github.com/DesignLiquido/delegua/pull/462) for aprovada e publicada, já vamos ter a definição de tipo melhor definida nas variáveis, constantes e funções, de inicio quero te pedir pra testar somente os tipos `texto`, `inteiro`, `real`, `vetor`, `qualquer`, `vazio`.

O tipo `lógico` eu ainda não implementei, vamos ver como vai ficar dessa forma por enquanto, depois termino a implementação com o tipo lógico também.
