### ISSUE TITLE
Adicionar aos estruturas de dados o tipo dos parametros e de funcoes e do retorno da função

### ISSUE THREAD

**Issue by ItaloCobains** [DesignLiquido/delegua#463]
Preciso ter o tipo de cada parametro na estrutura de dados para fazer o parse em AssemblyScript.
Tanto para os parametros quanto para o retorno da função.

![image](https://github.com/DesignLiquido/delegua/assets/83548040/bdf6d2db-121b-40bc-8a5c-e1f625f4d303)
![image](https://github.com/DesignLiquido/delegua/assets/83548040/3b8b8997-188f-4d3d-9055-720f4937c615)

**Comment by samuelrvg** [comment]
@ItaloCobains Essa PR já deve resolver https://github.com/DesignLiquido/delegua/pull/467

![image](https://github.com/DesignLiquido/delegua/assets/14062631/9f269b6e-2c34-4481-b960-7c43e142ad31)
