### ISSUE TITLE
Visual Alg - Erro em algoritmo Para

### ISSUE THREAD

**Issue by Priscilabier** [DesignLiquido/delegua#478]
Quando rodo esse código:

Para I <- 3 ate 10 faca

ele gera esse erro:
"Esperado palavra reservada 'de' após variáve de controle de 'para'."

**Comment by leonelsanchesdasilva** [comment]
Olá, @Priscilabier. Acredito que a sintaxe seja:

```
para I de 3 ate 10 faca
```

http://www.inf.ufsc.br/~bosco.sobral/ensino/ine5201/Visualg2_manual.pdf, página 10.

**Comment by samuelrvg** [comment]
> Olá, @Priscilabier. Acredito que a sintaxe seja:
> 
> ```
> para I de 3 ate 10 faca
> ```
> 
> http://www.inf.ufsc.br/~bosco.sobral/ensino/ine5201/Visualg2_manual.pdf, página 10.

@leonelsanchesdasilva No VisuAlg funciona normal, logo esse formato que ela passou também é válido.

![image](https://github.com/DesignLiquido/delegua/assets/14062631/3507a9a4-cb00-4f87-b3f7-b7719ee229a8)

**Comment by leonelsanchesdasilva** [comment]
Interessante. Vou implementar amanhã isso, então.

**Comment by leonelsanchesdasilva** [comment]
Corrigido em https://github.com/DesignLiquido/delegua/pull/481. Publicado na versão 0.7.18 da extensão.
