### ISSUE TITLE
Corrigir testes unitários

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#480]
Branch principal esta com os testes quebrando quando executamos `yarn testes-unitarios`.

![image](https://github.com/DesignLiquido/delegua/assets/14062631/1c5dd2d3-e53d-4680-a8bb-25945db8ff16)

**Comment by leonelsanchesdasilva** [comment]
Corrigido em https://github.com/DesignLiquido/delegua/pull/481
