### ISSUE TITLE
Adicionar validações de possível objeto em funções da biblioteca global do VisuAlg

### ISSUE THREAD

**Issue by thenicolau** [DesignLiquido/delegua#483]
Algumas funções do visualg estão somente aceitando um valor inteiro porem em alguns casos pode ser que venha um objeto com a propriedade valor, algumas funções ainda não possuem essa validacao

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva isso ainda existe? Se sim. Poderia explicar, acabei não entendendo muito do problema.

**Comment by leonelsanchesdasilva** [comment]
> @leonelsanchesdasilva isso ainda existe? Se sim. Poderia explicar, acabei não entendendo muito do problema.

@Aristidescosta. Sim, existe. 

Quando trabalhamos com outras bibliotecas, elas não possuem a estruturação de variáveis de Delégua: elas podem trabalhar com os tipos primitivos de JavaScript. Nós temos que adicionar isso manualmente. É basicamente este código:

```
const valorResolvido = valor.hasOwnProperty('valor') ? valor.valor : valor;
```

Alguns métodos possuem isso já implementado. Por exemplo: https://github.com/DesignLiquido/delegua/blob/principal/fontes/bibliotecas/dialetos/visualg/numerica.ts#L60

Mas não todas as funções possuem isso. A ideia dessa issue é implementar a resolução de valor em todas as bibliotecas de todos os dialetos, não apenas do VisuAlg, ou seja: https://github.com/DesignLiquido/delegua/tree/principal/fontes/bibliotecas

**Comment by leonelsanchesdasilva** [comment]
#610 implementa para Égua Clássico. Faltam dialetos ainda. https://github.com/DesignLiquido/delegua/tree/principal/fontes/bibliotecas/dialetos

**Comment by Aristidescosta** [comment]
> #610 implementa para Égua Clássico. Faltam dialetos ainda. https://github.com/DesignLiquido/delegua/tree/principal/fontes/bibliotecas/dialetos

Nos outros dialetos não implementei porque alguns já vêm com a tipagem correcta. E para aqueles que não têm a tipagem correcta, já existe uma validação.

**Comment by leonelsanchesdasilva** [comment]
> > #610 implementa para Égua Clássico. Faltam dialetos ainda. https://github.com/DesignLiquido/delegua/tree/principal/fontes/bibliotecas/dialetos
> 
> Nos outros dialetos não implementei porque alguns já vêm com a tipagem correcta. E para aqueles que não têm a tipagem correcta, já existe uma validação.

Ok, vou considerar esta issue como finalizada.
