### ISSUE TITLE
[SUGESTÃO] Complementar a README

### ISSUE THREAD

**Issue by hullimoraes** [DesignLiquido/delegua#489]
Inserir um texto na README colocando as vantagens de aprender uma linguagem de programação em português.

**Comment by leonelsanchesdasilva** [comment]
Olá, @hullimoraes. Obrigado pela sugestão. Gostaria de submeter uma PR, ou prefere que a gente decida o que colocar?

**Comment by cassfer** [comment]
Com esse commit #509 podemos finalizar essa issue.

**Comment by leonelsanchesdasilva** [comment]
Sensacional. Obrigado pela contribuição!
