### ISSUE TITLE
Implementar `limpatela`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#502]
```
Algoritmo "limpatela"
Var
Inicio
    escreva("teste")
    limpatela
    escreva("teste2")
Fimalgoritmo
```

**Comment by leonelsanchesdasilva** [comment]
Algumas ideias aqui:

- Para o vscode: `vscode.commands.executeCommand('workbench.action.terminal.clear');`
- Node: https://www.geeksforgeeks.org/node-js-console-clear-method/
