### ISSUE TITLE
Formas de uso da função `aleatorio`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#507]
Referência: https://www.clubedohardware.com.br/forums/topic/1401189-gerar-numero-aleatorio-no-visualg-de-0-a-5/

```
algoritmo "aleatorio"
var
   mes1, mes2 :inteiro

inicio
   escreval("Digite o mes do ano")

   aleatorio 1, 12
       leia(mes1)
       leia(mes2)
   aleatorio off

   escreval("")
   escreval("Mes 1:", mes1)
   escreval("Mes 2:", mes2)
fimAlgoritmo
```
Outra forma:

```
Algoritmo "Exemplo uso de listas do Visualg"
var
   nome  :caractere
   estado:caractere
   mes   :caractere

Inicio
   escreva ("Nome  : ")
   leia(nome)

   ALEATORIO ON
       escreva ("Estado: ")
       lista "ESTADOS"
       leia(estado)
       escreva ("MES   : ")
       lista "MESES"
       leia(mes)
   ALEATORIO OFF

   escreval()
   escreval()
   escreval("NOME  : ", nome)
   escreval("ESTADO: ", estado)
   escreval("MES   : ", mes)
Fimalgoritmo
```

**Comment by Aristidescosta** [comment]
@leonelsanchesdasilva, @samuelrvg isso deverá acontecer somente para o visualg ou em geral?

**Comment by leonelsanchesdasilva** [comment]
> @leonelsanchesdasilva, @samuelrvg isso deverá acontecer somente para o visualg ou em geral?

@Aristidescosta Esse comportamento é apenas para o VisuAlg. Não temos planos de implementar em outros dialetos.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva @Aristidescosta Pelos testes que realizei aqui, tanto na extensão quanto local, não esta funcionando o `aleatorio`, estou usando a versão mais recente de delégua `0.30.3`.

![Screenshot 2024-01-25 103002](https://github.com/DesignLiquido/delegua/assets/14062631/090de3fa-5047-4c36-a62c-3cdff7c67761)

**Comment by Aristidescosta** [comment]
> @leonelsanchesdasilva @Aristidescosta Pelos testes que realizei aqui, tanto na extensão quanto local, não esta funcionando o `aleatorio`, estou usando a versão mais recente de delégua `0.30.3`.
> 
> ![Screenshot 2024-01-25 103002](https://private-user-images.githubusercontent.com/14062631/299682472-090de3fa-5047-4c36-a62c-3cdff7c67761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTI1ODIsIm5iZiI6MTcwNjE5MjI4MiwicGF0aCI6Ii8xNDA2MjYzMS8yOTk2ODI0NzItMDkwZGUzZmEtNTA0Ny00YzM2LWE2MmMtM2NkZmY3YzY3NzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE0MTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMjc2MjZiMTNjNjY5NTJiZGFlNmRmZTFkZjcyMDJjZTc1YzNjNWYyZTVmMTE3MWMxMjQwMTg2ZGUxNGYzNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-onXDJmgHM_TyZHQ0w1zgfFEohxuPE3mPfdkduEmuhg)

Sim, estou trabalhando para a correcção deste erro.

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/delegua/pull/607.
