### ISSUE TITLE
Escreva está retornando `[object Object]`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#519]
```
var c = 1
escreva('Olá', algumTesteQualquer, 'Mundo!')
```
Saída: 
`[object Object]`

Possíveis soluções:
- Mostrar mensagem amigável para o usuário explicando motivo do problema.
- Ignorar variáveis que não existem dentro de `escreva`, ficando uma saída somente com o que é válido.
- Não executar enquanto não remover a variável inválida **(Acho que essa faz mais sentido)**.

**Comment by samuelrvg** [comment]
Próxima versão do Analisador Semântico já vai ser possível alertar que a variável não existe, veja o que foi feito [aqui](https://github.com/DesignLiquido/delegua/commit/b6a3f89a76307458187b4a0ff879a5e4db4d978d)

Mesmo com isso, ainda assim não impede o usuário de ter o retorno de `[object Object]`.

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Um voto para isso aqui:

> Não executar enquanto não remover a variável inválida.

**Comment by sukuasoft** [comment]
@samuelrvg
Posso trabalhar nesta issue?
 @aosccode

**Comment by samuelrvg** [comment]
> @samuelrvg Posso trabalhar nesta issue? @aosccode

@sukuasoft Pode!

**Comment by samuelrvg** [comment]
@sukuasoft Conseguiu progredir essa ISSUE? precisa de alguma ajuda?

**Comment by sukuasoft** [comment]
@samuelrvg Estou tendo dificuldade em executar qualquer algoritmo delegua, porque está informar inexistência do arquivo execucao.ts
Na raiz do projeto não contém o arquivo execucao.ts

**Comment by Aristidescosta** [comment]
@samuelrvg acabei de testar, e passou de boa.

**Comment by samuelrvg** [comment]
@Aristidescosta A ideia aqui é não deixar executar enquanto não resolver o problema, que nesse caso é a variável inválida, tanto para o terminal quanto execução pela extensão do vscode.

**Comment by Aristidescosta** [comment]
> @Aristidescosta A ideia aqui é não deixar executar enquanto não resolver o problema, que nesse caso é a variável inválida, tanto para o terminal quanto execução pela extensão do vscode.

Com as atualizações que foram feitas no analisador semântico, este erro foi corrigido.
Eis um exemplo
![Screenshot (203)](https://github.com/DesignLiquido/delegua/assets/69801513/cb477bb8-44de-4b2a-b1a7-e01fb2b26104)

**Comment by samuelrvg** [comment]
@Aristidescosta Realmente, na versão mais recente não acontece mais. Obrigado pela observação.
