### ISSUE TITLE
`a, b, c = leia_inteiros(2)` deve inicializar 3 listas com 2 inteiros cada

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/delegua#523]

**Comment by pablotdv** [comment]
@leonelsanchesdasilva essa atribuição múltipla do leia_inteiros (reais e textos) não existe no potigol.
Conforme documentação, somente o leia_inteiro (real, texto) implementam essa funcionalidade de inicializar múltiplas variáveis.
