### ISSUE TITLE
Melhorar testes unitários que chamam `escreva`

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#536]
Exemplo:

```ts
it('Método substituir()', async () => {
    const retornoLexador = lexador.mapear([
        "var str = \"olá mundo, olá universo\";",
        "var novaStr = str.substituir(||/olá/g||, \"oi\");",
        "escreva(novaStr);",
    ], -1);
    const retornoAvaliadorSintatico = avaliadorSintatico.analisar(retornoLexador, -1);

    interpretador.funcaoDeRetorno = (saida: any) => {
        expect(saida).toEqual('oi mundo, oi universo');
    };

    const retornoInterpretador = await interpretador.interpretar(retornoAvaliadorSintatico.declaracoes);

    expect(retornoInterpretador.erros).toHaveLength(0);
    });
})
```

Adicionar esse trecho abaixo a **todos** os testes unitários que tem `escreva(...)` sobrescrevendo assim a `funcaoDeRetorno` do interpretador e comparando com o esperado.

```ts
interpretador.funcaoDeRetorno = (saida: any) => {
    expect(saida).toEqual('oi mundo, oi universo');
};
```

**Comment by ItaloCobains** [comment]
@samuelrvg esse `escreva` é dos testes de delegua ou de outra linguagem ?

**Comment by ItaloCobains** [comment]
@samuelrvg @leonelsanchesdasilva conferem pra mim se dessa forma é valido para [testar muitos escrevas](https://github.com/DesignLiquido/delegua/compare/principal...536-melhorar-testes-unit%C3%A1rios-que-chamam-escreva).

**Comment by samuelrvg** [comment]
> @samuelrvg esse `escreva` é dos testes de delegua ou de outra linguagem ?

Delégua.

**Comment by samuelrvg** [comment]
@ItaloCobains Anima fazer dos demais dialetos?

**Comment by ItaloCobains** [comment]
@samuelrvg pode ser qual o próximo ?

**Comment by samuelrvg** [comment]
@ItaloCobains Todos que tem `escreva`, fique a vontade pra escolher qual dialeto começar, vamos fazer pra todos.

Se quiser pode abrir outras ISSUES e fazendo por partes.

**Comment by ItaloCobains** [comment]
@samuelrvg Ok.

**Comment by ItaloCobains** [comment]
@samuelrvg falta algumas ainda '-'

**Comment by ItaloCobains** [comment]
Irei fazer outras coisas terminarei o restante depois.

**Comment by samuelrvg** [comment]
Encerrando por hora, outro momento abrimos outra issue vinculada pra continuar caso precise.
