### ISSUE TITLE
doc: Sem documentação sobre como instalar delegua localmente para contribuidores

### ISSUE THREAD

**Issue by antonio-pedro99** [DesignLiquido/delegua#563]

**Comment by leonelsanchesdasilva** [comment]
@antonio-pedro99 Isso na verdade faz parte de outro repositório: https://github.com/DesignLiquido/delegua-node#instala%C3%A7%C3%A3o

[Precisei separar o projeto em dois numa altura do projeto](https://github.com/DesignLiquido/delegua-node/wiki#o-n%C3%BAcleo-da-linguagem): como Delégua precisa funcionar no navegador e no Node, um projeto virou dois.

Se isso for suficiente, me deixe saber, porque vou fechar a issue.

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 Isso na verdade faz parte de outro repositório: https://github.com/DesignLiquido/delegua-node#instala%C3%A7%C3%A3o
> 
> Precisei separar o projeto em dois numa altura do projeto: como Delégua precisa funcionar no navegador e no Node, um projeto virou dois.
> 
> Se isso for suficiente, me deixe saber, porque vou fechar a issue.

Seria legal mencionar isso no README do delegua?

**Comment by leonelsanchesdasilva** [comment]
> > @antonio-pedro99 Isso na verdade faz parte de outro repositório: https://github.com/DesignLiquido/delegua-node#instala%C3%A7%C3%A3o
> > Precisei separar o projeto em dois numa altura do projeto: como Delégua precisa funcionar no navegador e no Node, um projeto virou dois.
> > Se isso for suficiente, me deixe saber, porque vou fechar a issue.
> 
> Seria legal mencionar isso no README do delegua?

Isso já foi feito: https://github.com/DesignLiquido/delegua#instala%C3%A7%C3%A3o

**Comment by antonio-pedro99** [comment]
@leonelsanchesdasilva noite hhh era a pressāo da gravaçāo
