### ISSUE TITLE
[VisuAlg] Incidente incorreto ao utilizar a estrutura `para` na linguagem VisuAlg

### ISSUE THREAD

**Issue by Cruzney** [DesignLiquido/delegua#567]
![image](https://github.com/DesignLiquido/vscode/assets/51549038/b2e856cd-d611-4c30-a1c6-ef3c8d8048b4)

Neste ponto especifico o Para deveria ir para o número sequencial e que não acontece.

Abaixo demostro o mesmo código rodando corretamente no visual Log;

![image](https://github.com/DesignLiquido/vscode/assets/51549038/cf63c02b-a941-4104-9f42-12d8f4068410)

Obrigado!

**Comment by samuelrvg** [comment]
@Cruzney Obrigado pelo report, teria como postar o código completo em formato de texto pra facilitar a correção e testes ?

**Comment by Cruzney** [comment]
@samuelrvg , Sim segue, adianto que removi da linha 39 a 44 do print anteriro "VsCode" e funcionou conforme esperado, mas não ocorreu este incidente com código completo no visual G.
Obrigado!

```portugol
algoritmo "SomaImpares"
var
   X, Y, i, soma : inteiro
inicio
   escreva("Digite o primeiro número: ")
   leia(X)
   escreva("Digite o segundo número: ")
   leia(Y)
   soma <- 0
   i <- 0
   se X > Y entao
      para i de Y ate X faca
         se i % 2 <> 0 entao
            escreva(i)
            soma <- soma + i
         fimSe
      fimPara
   senao
   i <- 0
      para i de X ate Y faca
         se i % 2 <> 0 entao
            escreval(i)
            soma <- soma + i
         fimSe
      fimPara
   fimSe
   escreval(" A soma dos números ímpares entre ", X , " e ", Y , " é: " , soma)
fimalgoritmo
```

**Comment by leonelsanchesdasilva** [comment]
@Cruzney Não sei quanto tempo faz que isso foi testado, mas na versão 0.9.18 da extensão (versão 0.28.0 do núcleo de Delégua), usei o código da imagem e tive o seguinte:

![image](https://github.com/DesignLiquido/delegua/assets/53848829/53fcdcdc-474f-4bb3-a864-322d5669a825)

Este é o código usado:

```portugol
algoritmo "SomaImpares"
var
   X, Y, i, soma : inteiro
inicio
   escreva("Digite o primeiro número: ")
   leia(X)
   escreva("Digite o segundo número: ")
   leia(Y)
   soma <- 0
   se (X % 2 = 0) entao
      X <- X + 1
   senao
      se (Y % 2 = 0) entao
         Y <- Y + 1
      fimse
   fimse
   i <- 0
   se X > Y entao
      para i de Y ate X faca
         se i % 2 <> 0 entao
            escreva(i)
            soma <- soma + i
         fimSe
      fimPara
   senao
      i <- 0
      para i de X ate Y faca
         se i % 2 <> 0 entao
            escreval(i)
            soma <- soma + i
         fimSe
      fimPara
   fimSe
   escreval(" A soma dos números ímpares entre ", X , " e ", Y , " é: " , soma)
fimalgoritmo
```

Não consegui simular somando até 99. A meu ver, o comportamento está quase idêntico ao do VisuAlg original.

Se for necessário mais algum ajuste, ou se meu teste não estiver correto, favor reabrir a issue.
