### ISSUE TITLE
Erro faca-enquanto com negação

### ISSUE THREAD

**Issue by StelmoNetto** [DesignLiquido/delegua#595]
Olá. Obrigado pela nova ferramenta.
Encontrei dois problemas ao executar o código abaixo:
```
programa
{
    funcao inicio()
    {
        inteiro valor = 2
                
        logico eNegativo
        faca
        {
            escreva("Ok\t", valor,"\n")
            valor--
            eNegativo = valor < 0            
        }
        enquanto(nao eNegativo)
    }
}
```
1º falha ao executar a negação `enquanto(nao eNegativo)`
2º não existe formatação com caracteres especiais de tabulação e nova linha

**Comment by samuelrvg** [comment]
@StelmoNetto Obrigado pela ISSUE aberta, já estou resolvendo esse problema, logo mais confirmo aqui a versão com a correção.

**Comment by samuelrvg** [comment]
@StelmoNetto _bug_ resolvido, atualizar a extensão para versão `v0.10.3`.
