### ISSUE TITLE
Implementar template string

### ISSUE THREAD

**Issue by matheusOliv23** [DesignLiquido/delegua#60]

**Comment by leonelsanchesdasilva** [comment]
@AlessandroFMello Exemplo de implementação:

```js
console.log("Minha string tem ${variavel} valor.".replace(/\$\{(\w[\w]+)\}/g, function(textoInterpolado, novoValor){
    return textoInterpolado + novoValor;
}))
```

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/delegua/pull/133. Documentado em https://github.com/DesignLiquido/delegua/wiki/Estruturas-de-dados#interpola%C3%A7%C3%A3o-de-texto.
