### ISSUE TITLE
Operador tipo de não retorna o tipo de retorno de funções

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#604]
Resultado esperado:

```
  var letras = "abc"
      
  escreva(tipo de letras.tamanho())  // número
```

Resultado atual
```
  var letras = "abc"
      
  escreva(tipo de letras.tamanho())  // dicionário
```

**Comment by samuelrvg** [comment]
@JohnPetros Estava fazendo alguns testes com Javascript, com base nos seus exemplos, tanto o `tipo de` quanto o `typeof` do Javascript, não retornam o tipo de retorno das funções, mas sim se é `função`/`function`.

Pra fazer nesse formato, teriamos que analisar o tipo de retorno da função, não sei se faz muito sentido ter isso.

Teste do js:

```
let c = () => console.log('Olá Mundo!')
typeof c
'function'
```

Nos seus exemplo, o certo seria retornar `tipo de` como `'função'` o que ainda não esta acontecendo, mas irei atuar nisso.

**Comment by samuelrvg** [comment]
No seu caso, o uso correto para o resultado esperado seria algo assim:

```
  var letras = 'abc'
  var tamanhoLetras= letras.tamanho()   
  escreva(tipo de tamanhoLetras)  // número
```

**Comment by leonelsanchesdasilva** [comment]
> No seu caso, o uso correto para o resultado esperado seria algo assim:
> 
> ```
>   var letras = 'abc'
>   var tamanhoLetras= letras.tamanho()   
>   escreva(tipo de tamanhoLetras)  // número
> ```

@samuelrvg Não, o uso do exemplo do @JohnPetros está correto, e `tipo de` deve inferir o tipo após resolver o operador. Isso é um bug pertinente.

**Comment by samuelrvg** [comment]
Resolvido na PR: https://github.com/DesignLiquido/delegua/pull/606
