### ISSUE TITLE
[Delégua] É retornado erro ao verificar o tipo de funções nativas

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#605]
Caso eu tente usar o operador `tipo de` com funções que eu mesmo criei, o comportamento ocorre como esperado.

```
funcao somar() {
    retorna 2 + 2
}

escreva(tipo de somar) // função
```

Mas se for com uma função nativa é retornado erro.

```
escreva(tipo de escreva) // Erro: TypeError: Cannot read properties of null (reading 'aceitar')
```

**Comment by leonelsanchesdasilva** [comment]
Oi, @JohnPetros 👋 

Acho que faz algum tempo que você não atualiza a versão de Delégua por aí, não? Com certeza na versão mais recente (na data de hoje, 0.30.5), isso já foi resolvido. 

![image](https://github.com/DesignLiquido/delegua/assets/53848829/2617d52a-b16e-435e-a8e5-36d08094ecfe)

Experimente repetir o teste aí com as dependências atualizadas, e por favor me confirme se o bug ainda persiste, para eu fechar essa issue.

**Comment by JohnPetros** [comment]
Opa @leonelsanchesdasilva, na verdade estou falando de funções nativas com `escreva` e `leia` . Além disso, estou utilizando o delégua web para fazer os testes.

![image](https://github.com/DesignLiquido/delegua/assets/93893533/035025d4-fbd1-4328-b89f-0f6584be8e60)

**Comment by leonelsanchesdasilva** [comment]
> Opa @leonelsanchesdasilva, na verdade estou falando de funções nativas com `escreva` e `leia` . Além disso, estou utilizando o delégua web para fazer os testes.
> 
> ![image](https://private-user-images.githubusercontent.com/93893533/302054198-035025d4-fbd1-4328-b89f-0f6584be8e60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTAyMTEsIm5iZiI6MTcwNjk4OTkxMSwicGF0aCI6Ii85Mzg5MzUzMy8zMDIwNTQxOTgtMDM1MDI1ZDQtZmJkMS00MzI4LWI4OWYtMGY2NTg0YmU4ZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE5NTE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZWYwNDgxYjQwMGIzZmQ4ZDY3NWJmMzM5NjVhZjhjYjYyNmU1ZTM3M2Q2OTU0ZTkxYTMzMGI3NzQ5MDg4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wp5rkqIouWHMK1JUo-l1LzMCGaQhwjjkEr2mi-QLJ0g)

@JohnPetros Entendi. É que seu primeiro exemplo não é de uma função nativa. De fato, precisamos corrigir isso.
