### ISSUE TITLE
[Delégua] Implementar primitivas `dicionario.chaves()` e `dicionario.valores()`

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/delegua#618]
Exemplo:

```js
var meuDicionario = {"a": 1, "b": 2, "c": 3}
escreva(meuDicionario.chaves()) // ["a", "b", "c"]
escreva(meuDicionario.valores()) // [1, 2, 3]
```

**Comment by samuelrvg** [comment]
Resolvido no commit: https://github.com/DesignLiquido/delegua/commit/2c7b5cebd817e4de7cc55a5ea2ab3b76f8b7b812

**Comment by leonelsanchesdasilva** [comment]
Faltou os testes unitários. Reabrindo.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva https://github.com/DesignLiquido/delegua/blob/principal/testes/primitivas/primitivas-dicionario.test.ts ?
