### ISSUE TITLE
[Delégua] Transformar iteráveis em tuplas

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#629]
Haveria também uma função para transformar iteráveis em tuplas? Similar ao Python: 

```
lista = [1,2,3]
print(tuple(lista))
```

_Postado originalmente por @JohnPetros em https://github.com/DesignLiquido/delegua/discussions/617#discussioncomment-8357393_

**Comment by leonelsanchesdasilva** [comment]
@samuelrvg Sim, algo como:

```js
var lista = [1,2,3]
escreva(tupla(lista)) // [(1, 2, 3)]
```

**Comment by Aristidescosta** [comment]
@samuelrvg 
@leonelsanchesdasilva 

Neste momento eu acho isto meio complicado, isso porque já existe uma declaração `Tupla`, então meio que fico sem sem ter como criar uma outra `declaração`(caso necessário)

**Comment by leonelsanchesdasilva** [comment]
Implementado em https://github.com/DesignLiquido/delegua/pull/682.
