### ISSUE TITLE
[Delégua] `escreva()` sem argumentos, erro do Avaliador Sintatico não é exibido

### ISSUE THREAD

**Issue by Aristidescosta** [DesignLiquido/delegua#643]
Ao escrever de forma incorrecta ou incompleta as funções nativas ou declarações os erros adequados do `ErroAvaliadorSintatico` não são exibidos.

Ao invés disso retorna o seguinte: `TypeError: Cannot read properties of null (reading 'aceitar')`

```
while (this.atual < declaracoes.length) {
  declaracoes[this.atual].aceitar(this);
  this.atual++;
}
```

**Comment by leonelsanchesdasilva** [comment]
Consegui simular o problema com um `escreva` sem argumentos, ou seja:

```js
escreva()
```

Aqui temos dois problemas a serem resolvidos no núcleo de Delégua:

- `escreva()` emite `null` ao invés de dar erro. Isso é um problema no avaliador sintático;
- O analisador semântico deveria identificar corretamente que `escreva()` sem argumentos é inválido;

Um terceiro problema tem a ver com a extensão executando código que tenha erros na avaliação sintática, o que não deveria acontecer. 

![image](https://github.com/DesignLiquido/delegua/assets/53848829/cb271b92-872c-4f57-a536-e51efd3bf3cb)

Esse problema deve ser corrigido na extensão. Se não me engano, já havia algo antigamente que prevenia a execução de código com falhas na análise sintática, mas acho que isso precisa ser corrigido.
