### ISSUE TITLE
Erro ao executar escreva vazio

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#644]
Se eu executo `escreva()` vazio ocorre isso:

![image](https://github.com/DesignLiquido/delegua/assets/93893533/ba5bb634-fc89-41ff-9280-83da6beccfec)

**Comment by leonelsanchesdasilva** [comment]
@JohnPetros Curiosamente, esse erro foi reportado hoje um pouco mais cedo: https://github.com/DesignLiquido/delegua/issues/643
