### ISSUE TITLE
Problema no retorno de itens removido do método encaixar

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#645]
Se eu passar apenas um parâmetro no método `encaixar()` nenhum elemento é removido.

```
var elementos = ['Oscilador', 'Circuito', 'Modulador', 'Refrigerador']

var elementosRemovidos = elementos.encaixar(1)

escreva(elementosRemovidos)
escreva(elementos) // Oscilador,Circuito,Modulador,Refrigerador
```

**Comment by leonelsanchesdasilva** [comment]
@JohnPetros Esse eu acho que é mais uma melhoria do método original.

**Comment by Aristidescosta200** [comment]
@leonelsanchesdasilva essa issue já foi resolvida!

**Comment by samuelrvg** [comment]
Pelos testes que realizei em `delegua-web` essa issue parece já estar concluida.
