### ISSUE TITLE
Os zeros não estão sendo considerados na condição do laço para

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#652]
Se eu executo o código abaixo é feito apenas uma única iteração:

```
para (var i = 1; i < 1000; i++) {
    escreva('uma iteração')
}

```

![image](https://github.com/DesignLiquido/delegua/assets/93893533/d06de5f3-ef56-4246-9fc1-593cde85f259)

Provavelmente, os zeros do número `10000000` não estou sendo considerados.

Isso só ocorre quando uso o operador `menor que`, pois se eu utilizo o `menor ou igual a`, o bug não acontece.

**Comment by Aristidescosta** [comment]
@JohnPetros Não é que os `0s` não estão sendo considerados, mas oq acontece é que ele só está a reconhecer um número após o sinal `<`.

ex: 

```
para (var i = 1; i < 54; i++) {
    escreva('uma iteração')
}
```
retorna:
```
    escreva('uma iteração')
    escreva('uma iteração')
    escreva('uma iteração')
    escreva('uma iteração')
    escreva('uma iteração')
```

o mais interessante é que o problema parece resider apenas no sinal `<`


Vou dar uma olhada na possível correção do problema.
