### ISSUE TITLE
Erro ao chamar função que retorna uma lista contido em uma variável

### ISSUE THREAD

**Issue by JohnPetros** [DesignLiquido/delegua#653]
Se eu chamo uma função que retorna uma lista (que está em uma varíável e o retorno da função não está sendo imprimida) acontece o seguinte erro:

```
funcao retorneLista() {
  var lista = []

  retorna lista
}

retorneLista()
```

![image](https://github.com/DesignLiquido/delegua/assets/93893533/ba6dc3bc-5249-46f5-840c-05fb33572759)

**Comment by leonelsanchesdasilva** [comment]
@Aristidescosta Esta issue não foi resolvida pelo PR #656. Ao utilizar uma versão modificada do código:

```js
funcao retorneLista() {
  var lista = []

  retorna lista
}

escreva(retorneLista())
```

Obtive somente um `]`:

![image](https://github.com/DesignLiquido/delegua/assets/53848829/e7aeeeed-916c-4119-845c-fc41dce287fe)

**Comment by Aristidescosta200** [comment]
@leonelsanchesdasilva Vou aguardar a linkagem para poder fazer os testes correctos, e depois volto para a correção da issue.
