### ISSUE TITLE
Erro na hora de executar estrutura para no vscode

### ISSUE THREAD

**Issue by ItaloCobains** [DesignLiquido/delegua#677]
Ontem estava gravando um video basico com delegua e me deparei com o seguinte problema.

Para visulizar basta entrar nesse [site](https://trytech.app/pt-BR/cursos)  e rodar o video ate o minuto 38:04.

Pode muito bem ter sido erro meu, mas achei melhor informar.

Desde já agradeço.

**Comment by leonelsanchesdasilva** [comment]
Código:

```js
var numeros = []

funcao adicionarNumeros(numero, quantidadeDeVezes) {
    para (var i = 0; i < quantidadeDeVezes; i = i + 1) {
        numeros.adicionar(numero)
    }
}

adicionarNumeros(10, 5)
adicionarNumeros(2, 5)
adicionarNumeros(0, 5)
adicionarNumeros(14, 5)
adicionarNumeros(15, 5)
adicionarNumeros(20, 5)

escreva(numeros)
escreva(numeros.ordenar())
escreva(numeros.filtrarPor)
```

Funciona para execução normal. Falha com depuração.
