### ISSUE TITLE
Problema no lexador.mapear()

### ISSUE THREAD

**Issue by samuelrvg** [DesignLiquido/delegua#86]
Dado o seguinte array de string:

['5*4', 'escreva(2 + 2)']

Saída:
4
Esperado:
20
4

Esse problema ocorre no seguinte método `analisarNumero()` do arquivo `lexador.ts`:

```
        const numeroCompleto = this.codigo[this.linha].substring(
            this.inicioSimbolo,
            this.atual
        );
        this.adicionarSimbolo(
            tiposDeSimbolos.NUMERO,
            parseFloat(numeroCompleto)
        );
```

A variável `numeroCompleto` era pra retornar 4, mas esta retornando vazio, e quando tenta fazer o parseFloat gera `NaN`;

Testando, verifiquei que `this.atual` esta com valor errado.

**Comment by samuelrvg** [comment]
Se colocar um ponto e vírgula no final, funciona normal.

ex: `['5*4;', 'escreva(2 + 2)']`

**Comment by leonelsanchesdasilva** [comment]
Usando esta entrada:

```['5*4', 'escreva(2 + 2)']```

O problema não faz muito sentido, porque estamos colocando dois textos dentro de um vetor. 

Considerando outra construção:

```[5*4, escreva(2 + 2)]```

`escreva()` não retorna valor. Retornar valor é diferente de escrever na saída. Por isso o erro.

**Comment by samuelrvg** [comment]
@leonelsanchesdasilva,

Essa entrada: 

`['5*4', 'escreva(2 + 2)']`

Faz sentido pois o lexador aceita um array de string, quem vai lidar no final se mostra ou não resultado é o interpretador com base nas declarações vindas do lexador.

https://github.com/DesignLiquido/delegua/issues/86#issuecomment-1122800388

**Comment by leonelsanchesdasilva** [comment]
Fechando após esclarecer que não há problema com o lexador para a expressão apresentada.
